[package]
name = "pong-rust"
version = "0.1.0"
authors = ["bwallberg <me@bwallberg.com>"]

[dependencies]
piston = "0.26.0"
piston2d-graphics = "0.19.0"
pistoncore-glutin_window = "0.31.0"
piston2d-opengl_graphics = "0.36.0"
rand = "0.3.14"